# .readthedocs.yml

# Required
version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally set the version of Python and requirements required to build your docs
python:
  version: "3.8" 