site_name: Hướng dẫn sử dụng hệ thống vContract

nav:
    - 'Trang chủ': 'index.md'
    - 'vContract - Hợp đồng điện tử': 
        - 'Thiết lập luồng ký hợp đồng': 'vContract/thiet-lap-luong-ky.md'
        - 'Chức năng cơ bản cho doanh nghiệp': 'vContract/chuc-nang-co-ban-cho-doanh-nghiep.md'
        - 'Chức năng hợp đồng': 'vContract/chuc-nang-hop-dong.md'   
        - 'Chức năng lập hợp đồng mẫu cơ bản': 'vContract/lap_hop_dong_theo_mau_co_ban.md'        
    - 'Release Notes': 'release-notes.md'
theme:
    name: readthedocs
    navigation_depth: 100
    highlightjs: true
extra_css:
    - css/extra.css
extra_javascript:
    - js/extra.js
copyright: Prepared by <a href="https://hopdongdientu.viettel.vn/">vContract - Viettel.</a>